"""
notifier.py — Sends digest via email and/or Telegram.

WITHOUT credentials: prints a summary to the terminal (always works).
WITH SENDER_EMAIL + SENDER_PASSWORD: sends a full HTML email digest.
WITH TELEGRAM_BOT_TOKEN + TELEGRAM_CHAT_ID: sends a Telegram ping.
"""

import os
import smtplib
from html import escape
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime

SENDER_EMAIL      = os.getenv("SENDER_EMAIL", "")
SENDER_PASSWORD   = os.getenv("SENDER_PASSWORD", "")
RECIPIENT_EMAIL   = os.getenv("RECIPIENT_EMAIL", "")
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID   = os.getenv("TELEGRAM_CHAT_ID", "")


def _print_digest(jobs: list[dict]) -> None:
    """Always-available fallback — prints digest to terminal."""
    print("\n" + "="*60)
    print(f"PM JOB DIGEST — {datetime.now().strftime('%d %b %Y')}")
    print(f"{len(jobs)} high-fit role(s) found")
    print("="*60)
    for j in jobs:
        print(f"\n  {j['score']:.1f}/10  {j['title']} @ {j['company']}")
        print(f"         {j['location']} — {j['url']}")
        print(f"         {j['fit_summary']}")
    print("\nOpen the dashboard to review: python main.py --dashboard\n")


def _build_html(jobs: list[dict]) -> str:
    today = datetime.now().strftime("%d %b %Y")
    cards = ""
    for raw in jobs:
        # Job data comes from scraped pages, so escape everything before putting it in HTML
        j = {k: (escape(v, quote=True) if isinstance(v, str) else v) for k, v in raw.items()}
        score = j["score"]
        sc = "#C0DD97" if score >= 8 else "#FAC775" if score >= 6.5 else "#F7C1C1"
        stc = "#27500A" if score >= 8 else "#633806" if score >= 6.5 else "#791F1F"
        reqs = "".join(f"<li>{escape(str(r))}</li>" for r in j.get("key_requirements", []))
        cards += f"""
<div style="border:1px solid #e5e3db;border-radius:12px;padding:24px;margin-bottom:20px;">
  <div style="display:flex;justify-content:space-between;align-items:flex-start;gap:12px;">
    <div>
      <h2 style="margin:0 0 4px;font-size:17px;color:#1a1a18;">{j['title']}</h2>
      <p style="margin:0;color:#5f5e5a;font-size:13px;">{j['company']} &middot; {j.get('location') or ''}</p>
    </div>
    <span style="background:{sc};color:{stc};padding:4px 12px;border-radius:20px;
                 font-size:13px;font-weight:600;white-space:nowrap;">{score:.1f}/10</span>
  </div>
  <p style="margin:12px 0 8px;color:#3d3d3a;font-size:14px;line-height:1.6;">{j['fit_summary']}</p>
  {('<ul style="margin:0 0 12px;padding-left:18px;color:#3d3d3a;font-size:13px;">' + reqs + '</ul>') if reqs else ''}
  <a href="{j['url'] if (j.get('url') or '').startswith(('http://', 'https://')) else '#'}" style="display:inline-block;padding:8px 16px;background:#534AB7;
     color:#fff;text-decoration:none;border-radius:8px;font-size:13px;margin-bottom:16px;">View job →</a>
  <details style="margin-top:4px;">
    <summary style="cursor:pointer;font-size:13px;font-weight:500;color:#3d3d3a;padding:8px 0;
                    border-top:1px solid #e5e3db;">Cover letter (ready to send)</summary>
    <p style="font-size:13px;color:#5f5e5a;margin:8px 0 4px;"><strong>Subject:</strong> {j.get('cover_letter_subject','')}</p>
    <div style="background:#f8f7f4;border-radius:8px;padding:14px;font-size:13px;
                line-height:1.7;color:#3d3d3a;white-space:pre-wrap;">{j.get('cover_letter_body','')}</div>
  </details>
</div>"""

    return f"""<!DOCTYPE html><html><body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
max-width:660px;margin:0 auto;padding:24px;background:#fff;">
<h1 style="font-size:20px;font-weight:500;color:#1a1a18;margin-bottom:4px;">Job Digest — {today}</h1>
<p style="color:#5f5e5a;font-size:14px;margin:0 0 24px;">{len(jobs)} high-fit role(s) found today across Naukri, LinkedIn & company sites.</p>
{cards}
<p style="color:#888780;font-size:12px;border-top:1px solid #e5e3db;padding-top:16px;margin-top:24px;">
Generated by Job Hunter Board. Edit your resume in your profile settings to improve scores.</p>
</body></html>"""


def recipient_for_user(user_id: int) -> str:
    """Where a user's emails go: their sign-in email, else the Gmail they connected for sync.
    The admin account (id 1) falls back to RECIPIENT_EMAIL / SENDER_EMAIL."""
    try:
        from db import get_conn, DB_PATH
        conn = get_conn(DB_PATH)
        row = conn.execute("SELECT email, imap_email, username FROM users WHERE id = ?", (user_id,)).fetchone()
        conn.close()
    except Exception as e:
        print(f"  [Email] Could not look up recipient for user {user_id}: {e}")
        return ""
    if row:
        for candidate in (row[0], row[1], row[2]):
            if candidate and "@" in candidate and " " not in candidate and not candidate.endswith(("_google", "_linkedin")):
                return candidate
    if user_id == 1:
        return RECIPIENT_EMAIL or SENDER_EMAIL
    return ""


def send_email_digest(jobs: list[dict], recipient: str = None) -> bool:
    """Sends the digest to `recipient`. With no recipient (CLI runs for the operator),
    it goes to RECIPIENT_EMAIL / SENDER_EMAIL."""
    if not jobs:
        return False
    if not SENDER_EMAIL or not SENDER_PASSWORD:
        print("  [Email] No credentials set — skipping. Add SENDER_EMAIL + SENDER_PASSWORD to .env")
        return False

    recipient = recipient or RECIPIENT_EMAIL or SENDER_EMAIL
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Job matches — {len(jobs)} today ({datetime.now().strftime('%d %b')})"
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient
    msg.attach(MIMEText(_build_html(jobs), "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as srv:
            srv.login(SENDER_EMAIL, SENDER_PASSWORD)
            srv.sendmail(SENDER_EMAIL, recipient, msg.as_string())
        print(f"  [Email] Digest sent to {recipient}")
        return True
    except Exception as e:
        print(f"  [Email] Failed: {e}")
        return False


def send_email(recipient: str, subject: str, html: str) -> bool:
    """Sends one HTML email from SENDER_EMAIL. Returns False when email isn't configured or fails."""
    if not SENDER_EMAIL or not SENDER_PASSWORD or not recipient:
        return False
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient
    msg.attach(MIMEText(html, "html"))
    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465, timeout=20) as srv:
            srv.login(SENDER_EMAIL, SENDER_PASSWORD)
            srv.sendmail(SENDER_EMAIL, recipient, msg.as_string())
        return True
    except Exception as e:
        print(f"  [Email] Failed to send '{subject}': {e}")
        return False


def email_configured() -> bool:
    return bool(SENDER_EMAIL and SENDER_PASSWORD)


def send_telegram_ping(jobs: list[dict]) -> None:
    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
        return
    try:
        import requests as req
        text = f"*PM Job Digest — {datetime.now().strftime('%d %b')}*\n{len(jobs)} high-fit role(s):\n\n"
        for j in jobs[:5]:
            text += f"• *{j['title']}* @ {j['company']} — {j['score']:.1f}/10\n"
        if len(jobs) > 5:
            text += f"_...and {len(jobs)-5} more_"
        req.post(
            f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
            json={"chat_id": TELEGRAM_CHAT_ID, "text": text, "parse_mode": "Markdown"},
            timeout=8,
        )
        print("  [Telegram] Ping sent")
    except Exception as e:
        print(f"  [Telegram] {e}")


def notify(jobs: list[dict], user_id: int = None) -> None:
    _print_digest(jobs)        # always runs
    if user_id is None or user_id == 1:
        send_email_digest(jobs)    # operator's own digest, if credentials set
        send_telegram_ping(jobs)   # the Telegram chat is the operator's, so only their digest goes there
    else:
        to = recipient_for_user(user_id)
        if to:
            send_email_digest(jobs, recipient=to)
